# Пример конфигурации sysctl-hardening для production сервера
device:
  layer: rpi5
  hostname: production-server

image:
  layer: image-rpios
  name: production-sysctl-hardened
  compression: zstd

layer:
  base: bookworm-minbase
  security: sysctl-hardening

# Полная настройка sysctl hardening для production
sysctl_hardening:
  enable: y                        # Включить hardening
  ptrace_restrict: y              # Ограничить ptrace
  aslr_enable: y                  # Включить ASLR
  tcp_syn_cookies: y              # TCP SYN cookies
  source_route_validation: y      # Source route validation
  core_dump_restrict: y           # Ограничить core dumps
  icmp_redirect_ignore: y         # Игнорировать ICMP redirects
  source_routed_packets_ignore: y # Игнорировать source routed пакеты
  broadcast_requests_ignore: y    # Игнорировать broadcast запросы
  icmp_echo_ignore_broadcasts: y  # Игнорировать ICMP echo к broadcast
  log_martian_packets: y          # Логировать martian пакеты

# Дополнительные security слои
layer:
  base: bookworm-minbase
  security: apparmor
  security: ufw
  security: auditd

# AppArmor для Mandatory Access Control
apparmor:
  enable: y
  mode: enforce
  system_monitoring: y

# Firewall для сетевой защиты
ufw:
  enable: y
  default_incoming: deny
  default_outgoing: allow
  allow_services: ssh,http,https
  logging: medium

# Audit daemon для системного мониторинга
auditd:
  enable: y
  max_log_file: 8
  space_left: 75
  flush: incremental_async
