# Test configuration for RAID overlay layer
device:
  layer: rpi5
  hostname: raid-overlay-test
  user1: pi

image:
  layer: raid  # Our new RAID overlay layer
  name: raid-overlay-test
  rootfs_type: ext4
  boot_part_size: 100M
  root_part_size: 2G

# RAID overlay configuration
raid:
  level: RAID1      # RAID0 or RAID1
  devices: 2        # Number of external drives (1-4)
  sdcard_size: 200M # SD card boot partition size
  external_size: 1G # Size per external drive partition

layer:
  base: bookworm-minbase
  build: sys-build-base
