# Тестовая конфигурация для hybrid-raid-layout
---
device:
  layer: rpi5

image:
  layer: hybrid-raid-layout
  # Настройки гибридного RAID1 хранилища
  IGconf_hybrid_raid_luks_rootfs_type: ext4
  IGconf_hybrid_raid_luks_encryption_enabled: n
  IGconf_hybrid_raid_luks_ssd_ids: "ata-SAMSUNG_HD204UI_S1XWJ1LZ100000,ata-SAMSUNG_HD204UI_S1XWJ1LZ100001"
  IGconf_hybrid_raid_luks_boot_part_size: 200M
  IGconf_hybrid_raid_luks_root_part_size: 2G
  IGconf_hybrid_raid_luks_pmap: clear

layer:
  base: bookworm-minbase
