# Example configuration for Raspberry Pi OS Base Image Layer
#
# This layer downloads official Raspberry Pi OS images and uses them
# as a base for further customization

device:
  layer: rpi5

image:
  layer: standard
  name: raspios-custom

# Use Raspberry Pi OS Base Image Layer
layer:
  base: raspios-base

# Configure the base image download
raspios_base_image_url: https://downloads.raspberrypi.com/raspios_lite_arm64/images/raspios_lite_arm64-2025-10-02/2025-10-01-raspios-trixie-arm64-lite.img.xz

# SHA256 verification (recommended)
# Method 1: Auto-download SHA256 file
raspios_base_image_sha256_url: https://downloads.raspberrypi.com/raspios_lite_arm64/images/raspios_lite_arm64-2025-10-02/2025-10-01-raspios-trixie-arm64-lite.img.xz.sha256

# Method 2: Direct SHA256 (alternative)
# raspios_base_image_sha256: "put_actual_sha256_here"

# Optional configuration
raspios_base_cache_dir: ./cache              # Cache directory
raspios_base_verify_checksum: y              # Verify SHA256
raspios_base_force_redownload: n             # Force re-download
raspios_base_extract_format: auto            # auto, xz, gz, zip, none
raspios_base_target_device: rpi5             # Target device

# Add additional layers on top of base image
layers:
  # Security hardening
  - security/apparmor
  - security/ufw
  - security/auditd
  
  # System tools
  - sys-apps/systemd-chrony-min
  
  # Application layers
  - net-misc/cockpit

---

# Additional configuration examples:

# Example 1: Minimal Raspberry Pi OS with security
device:
  layer: rpi5

image:
  layer: standard
  name: raspios-secure

layer:
  base: raspios-base

raspios_base_image_url: https://downloads.raspberrypi.com/raspios_lite_arm64/images/raspios_lite_arm64-2025-10-02/2025-10-01-raspios-trixie-arm64-lite.img.xz
raspios_base_image_sha256_url: https://downloads.raspberrypi.com/raspios_lite_arm64/images/raspios_lite_arm64-2025-10-02/2025-10-01-raspios-trixie-arm64-lite.img.xz.sha256

layers:
  - security-suite

---

# Example 2: Raspberry Pi OS for development
device:
  layer: rpi5

image:
  layer: standard
  name: raspios-dev

layer:
  base: raspios-base

raspios_base_image_url: https://downloads.raspberrypi.com/raspios_lite_arm64/images/raspios_lite_arm64-2025-10-02/2025-10-01-raspios-trixie-arm64-lite.img.xz
raspios_base_verify_checksum: n  # Skip verification for dev
raspios_base_cache_dir: /tmp/cache

layers:
  - sys-devel/gnu-common
  - app-container/distrobox

---

# Example 3: Enterprise Raspberry Pi OS
device:
  layer: rpi-cm5
  variant: 8G

image:
  layer: standard
  name: raspios-enterprise

layer:
  base: raspios-base

# Use internal mirror
raspios_base_image_url: https://internal-mirror.company.com/raspios-trixie.img.xz
raspios_base_image_sha256: "verified_checksum_from_security_team"
raspios_base_verify_checksum: y
raspios_base_force_redownload: n

layers:
  - security-suite
  - net-misc/cockpit
  - app-misc/rpi5-server-config

---

# Available official images:
#
# Raspberry Pi OS Lite (ARM64) - Recommended
# https://downloads.raspberrypi.com/raspios_lite_arm64/images/
#
# Raspberry Pi OS Desktop (ARM64)
# https://downloads.raspberrypi.com/raspios_arm64/images/
#
# Raspberry Pi OS Full (ARM64)
# https://downloads.raspberrypi.com/raspios_full_arm64/images/
#
# Legacy Bullseye/Bookworm releases
# https://downloads.raspberrypi.com/raspios_oldstable_lite_arm64/images/
#
# Always check official website for latest versions:
# https://www.raspberrypi.com/software/operating-systems/

