# Пример конфигурации sudo-logging для enterprise системы
device:
  layer: rpi5
  hostname: enterprise-server

image:
  layer: image-rpios
  name: enterprise-sudo-logging
  compression: zstd

layer:
  base: bookworm-minbase
  security: sudo-logging

# Полная настройка sudo логирования для enterprise
sudo_logging:
  enable: y                              # Включить логирование
  log_file: /var/log/sudo.log           # Файл для детальных логов
  log_format: "%h %e[%u] %t : %p ; %a : TTY=%t ; PWD=%d ; USER=%u ; TSID=%s ; COMMAND=%c"
  syslog_enable: y                      # Дублировать в syslog
  syslog_facility: authpriv             # Facility для syslog
  syslog_priority: notice               # Priority для syslog
  auth_timeout: 30                      # 30 минут аутентификации
  timestamp_timeout: 30                 # 30 минут timestamp
  passwd_timeout: 5                     # 5 минут для пароля
  badpass_message: "Authentication failed. Please contact administrator."
  lecture: once                         # Показывать лекцию один раз
  insults: n                            # Без insults
  requiretty: n                         # Не требовать TTY
  visiblepw: n                          # Не показывать пароль
  loglinelen: 0                         # Без ограничений длины
  compresslogs: y                       # Сжимать старые логи
  maxlogsize: 100M                      # Ротация при 100MB

# Дополнительные security слои
layer:
  base: bookworm-minbase
  security: apparmor
  security: ufw
  security: auditd
  security: sysctl-hardening
  security: pam-hardening
  security: password-policies

# AppArmor для MAC
apparmor:
  enable: y
  mode: enforce
  rpi_optimized: y

# Firewall
ufw:
  enable: y
  default_incoming: deny
  default_outgoing: allow
  allow_services: ssh,http,https
  logging: medium

# Audit daemon
auditd:
  enable: y
  max_log_file: 8
  space_left: 75

# System hardening
sysctl_hardening:
  enable: y
  ptrace_restrict: y
  aslr_enable: y
  tcp_syn_cookies: y

# PAM hardening
pam_hardening:
  enable: y
  pwquality_enable: y
  pwquality_minlen: 16
  pwquality_dcredit: -1
  pwquality_ucredit: -1
  pwquality_lcredit: -1
  pwquality_ocredit: -1
  pwquality_retry: 3
  faillock_enable: y
  faillock_deny: 5
  faillock_unlock_time: 900
  limits_enable: y

# Password policies
password_policies:
  enable: y
  pass_max_days: 60
  pass_min_days: 7
  pass_warn_age: 14
  inactive: 15
  account_expiry: 180
  root_password_expiry: 30
  lock_inactive_users: y
  password_history_remember: 10
