# Enterprise Industrial Automation RAID Configuration
# Optimized for SCADA systems with high availability and reliability

device:
  layer: rpi4
  class: pi4
  variant: industrial

image:
  layer: mdraid1-external-root
  name: industrial-scada-controller
  mdraid1_external_root_rootfs_type: ext4      # ext4 for maximum compatibility
  mdraid1_external_root_boot_part_size: 512M   # Large boot for industrial software
  mdraid1_external_root_root_part_size: 128G   # Massive storage for industrial data
  mdraid1_external_root_raid_level: RAID1     # Maximum performance and redundancy
  mdraid1_external_root_raid_devices: 2        # Full RAID1 for enterprise reliability (2 devices for RAID1)
  mdraid1_external_root_encryption_enabled: y  # Mandatory for industrial security
  mdraid1_external_root_sector_size: 4096      # Advanced format industrial drives
  mdraid1_external_root_compression: zstd      # Optimized for industrial workloads
  mdraid1_external_root_pmap: crypt           # Secure encrypted deployment

  # Performance optimizations for industrial use case
  mdraid1_external_root_apt_cache: y              # Fast package installation
  mdraid1_external_root_ccache: y                 # Cross-compilation optimization
  mdraid1_external_root_ccache_size: 20G          # Very large cache for industrial builds
  mdraid1_external_root_parallel_jobs: 8          # High parallel processing
  mdraid1_external_root_image_size_optimization: y # Optimize for deployment

layer:
  base: bookworm-minbase
  industrial: plc-integration
  protocols: industrial-protocols
  safety: industrial-safety
  monitoring: industrial-monitoring
  realtime: industrial-realtime
  security: industrial-security
  compliance: industrial-compliance

industrial:
  plc_communication: y
  modbus_support: y
  profibus_support: y
  industrial_io: y
  fieldbus_protocols: y
  device_integration: y

protocols:
  modbus_tcp: y
  modbus_rtu: y
  dnp3: y
  opc_ua: y
  ethernet_ip: y
  profinet: y

safety:
  emergency_stop: y
  safety_interlocks: y
  fault_detection: y
  safety_monitoring: y
  sil_certification: y

monitoring:
  plc_monitoring: y
  system_health: y
  predictive_maintenance: y
  alarm_management: y
  data_collection: y
  reporting: y

realtime:
  hard_realtime: y
  deterministic_timing: y
  priority_scheduling: y
  watchdog_timers: y
  low_latency_networking: y

security:
  industrial_compliant: y
  encryption_mandatory: y
  secure_boot: y
  audit_trails: y
  access_control: y

compliance:
  industrial_standards: y
  iec_61508: y
  iso_13849: y
  regulatory_compliance: y

# Enterprise integration
enterprise:
  scada_system: ignition
  historian_database: influxdb
  monitoring_platform: prometheus_grafana
  deployment_automation: ansible
  configuration_management: chef
  asset_management: itam
  ticketing_system: jira
