# Пример конфигурации для Raspberry Pi 5 серверной оптимизации
device:
  layer: rpi5
  hostname: rpi5-server
  storage_type: nvme  # Для максимальной производительности с NVMe SSD
  user1: admin
  user1pass: SecurePass123!

image:
  layer: image-rpios
  name: rpi5-server-optimized
  compression: zstd

layer:
  device: rpi5-server-config
  base: bookworm-minbase
  security: system-monitoring
  sbom: sbom-base

# Настройки серверной оптимизации
rpi5_server:
  disable_hdmi: y
  disable_wifi: y
  disable_bluetooth: y
  disable_audio: y
  pcie_max_speed: y
  usb_max_performance: y
  disable_unused_interfaces: y
  # Дополнительные возможности (опционально)
  optimize_performance: n    # Включить для максимальной производительности
  security_hardening: n      # Включить для повышенной безопасности

# Дополнительные настройки безопасности
security:
  enable_encryption: y
  secure_boot: y

# SBOM генерация для compliance
sbom:
  enable: y
  provider: syft

---
# Пример конфигурации для высокопроизводительного сервера
device:
  layer: rpi5
  hostname: rpi5-performance-server
  storage_type: nvme
  user1: admin

image:
  layer: image-rpios
  name: rpi5-performance-server
  compression: zstd

layer:
  device: rpi5-server-config
  base: bookworm-minbase

# Максимальная производительность
rpi5_server:
  disable_hdmi: y
  disable_wifi: y
  disable_bluetooth: y
  disable_audio: y
  pcie_max_speed: y
  usb_max_performance: y
  disable_unused_interfaces: y
  optimize_performance: y    # Максимальная производительность
  security_hardening: n      # Не используем для максимальной производительности

---
# Пример конфигурации для безопасного сервера
device:
  layer: rpi5
  hostname: rpi5-secure-server
  storage_type: nvme
  user1: admin

image:
  layer: image-rpios
  name: rpi5-secure-server
  compression: zstd

layer:
  device: rpi5-server-config
  base: bookworm-minbase
  security: system-monitoring

# Максимальная безопасность
rpi5_server:
  disable_hdmi: y
  disable_wifi: y
  disable_bluetooth: y
  disable_audio: y
  pcie_max_speed: y
  usb_max_performance: y
  disable_unused_interfaces: y
  optimize_performance: n    # Не используем для максимальной безопасности
  security_hardening: y      # Максимальная безопасность

security:
  enable_encryption: y
  secure_boot: y
  tpm_required: y

---
# Тестовая конфигурация для валидации
device:
  layer: rpi5
  class: pi5

layer:
  device: rpi5-server-config

# Минимальная конфигурация для тестирования
rpi5_server:
  disable_hdmi: y
  pcie_max_speed: y
