# Пример конфигурации auditd для enterprise системы
device:
  layer: rpi5
  hostname: enterprise-server

image:
  layer: image-rpios
  name: enterprise-audit-system
  compression: zstd

layer:
  base: bookworm-minbase
  security: auditd

# Полная конфигурация auditd для enterprise compliance с Raspberry Pi 5 поддержкой
auditd:
  enable: y                    # Включить auditd
  max_log_file: 10            # Хранить 10 лог файлов
  max_log_file_action: keep_logs  # Сохранять все логи
  space_left: 100             # 100MB свободного места
  space_left_action: syslog   # Логировать в syslog при нехватке места
  admin_space_left: 75        # 75MB для админа
  admin_space_left_action: single  # Single user mode при критической нехватке
  disk_full_action: halt      # Остановить систему при полном диске
  disk_error_action: syslog   # Логировать ошибки диска
  flush: sync                 # Синхронный сброс для максимальной надежности
  freq: 20                    # Высокая частота для детального мониторинга
  num_logs: 10                # 10 ротаций логов
  dispatcher: /sbin/audispd   # Стандартный диспетчер
  name_format: hostname       # Именование по hostname

  # Мониторинг современных компонентов Raspberry Pi 5
  monitoring_integration: y   # Интеграция с системами мониторинга
  compliance_mode: y          # Расширенные правила compliance (PCI-DSS, HIPAA)
  anomaly_detection: n        # Обнаружение аномалий (опционально)

# Дополнительные security слои для полной защиты
layer:
  base: bookworm-minbase
  security: apparmor
  security: ufw
  security: fail2ban

# AppArmor для MAC
apparmor:
  enable: y
  mode: enforce
  system_monitoring: y

# Firewall
ufw:
  enable: y
  default_incoming: deny
  default_outgoing: allow
  allow_services: ssh,http,https
  logging: medium

# Fail2ban для защиты от brute force
fail2ban:
  enable: y
  backend: systemd
  log_level: INFO
  db_purge_age: 1d
  default_ban_time: 10m
  default_find_time: 10m
  default_max_retry: 5
  enabled_jails: sshd,dropbear
  ban_action: iptables-multiport
