# Пример полной конфигурации с AppArmor для Raspberry Pi
# Mandatory Access Control с оптимизациями для Raspberry Pi платформы

device:
  layer: rpi5
  hostname: secure-rpi
  user1: admin
  user1pass: SecurePass123!

image:
  layer: image-rpios
  name: rpi-apparmor-secure
  compression: zstd

layer:
  base: bookworm-minbase
  security: apparmor
  monitoring: system-monitoring
  container: docker-runtime
  sbom: sbom-base

# Полная конфигурация AppArmor для production окружения с Raspberry Pi 5 поддержкой
apparmor:
  enable: y                    # Включить AppArmor
  mode: enforce                # Режим блокировки нарушений
  system_monitoring: y         # Системные оптимизации
  profiles_enable: y           # Установить кастомные профили
  initramfs_integration: y     # Интеграция с initramfs
  logging_enable: y            # Включить логирование
  container_support: y         # Поддержка контейнеров
  monitoring_support: y        # Поддержка мониторинга
  audit_integration: n         # Интеграция с auditd (опционально)

# Мониторинг системы
monitoring:
  prometheus: y
  grafana: y
  node_exporter: y

# Контейнерная среда
container:
  docker: y
  podman: y

# SBOM для аудита и compliance
sbom:
  enable: y
  provider: syft
  detailed_scan: y

# Дополнительные меры безопасности (опционально)
# security:
#   enable_encryption: y
#   secure_boot: y
