# Тестовая конфигурация для проверки hybrid-raid-luks функциональности
# Включает параметры тестирования RAID1 + LUKS шифрования

# ============================================================================
# ПАРАМЕТРЫ HYBRID-RAID-LUKS СЛОЯ
# ============================================================================

hybrid_raid_luks:
  # Базовые параметры файловой системы
  rootfs_type: ext4              # Тип корневой ФС (ext4, btrfs, f2fs)
  root_part_size: 2G             # Размер root раздела

  # Параметры шифрования LUKS
  encryption_enabled: y          # Включить LUKS шифрование
  key_method: file               # Метод хранения ключа
  key_size: 512                  # Размер ключа LUKS (бит)

  # Параметры RAID
  ssd_devices: /dev/sda,/dev/sdb # SSD устройства для RAID1

  # Дополнительные параметры
  boot_part_size: 200M           # Размер boot раздела
  pmap: clear                    # Тип provision map
  disk_expansion_enabled: y      # Включить авто-расширение диска

# ============================================================================
# КОНФИГУРАЦИЯ УСТРОЙСТВА И ОБРАЗА
# ============================================================================

device:
  layer: rpi5

image:
  layer: hybrid-raid-luks
  # Имя образа
  name: test-hybrid-raid-luks

# ============================================================================
# СЛОИ СИСТЕМЫ
# ============================================================================

layer:
  base: trixie-minbase
  raid_luks: raid-luks
