# Тестовая конфигурация для проверки hybrid-raid-layout функциональности
# Включает параметры тестирования RAID1 + LUKS шифрования

# ============================================================================
# ПЕРЕМЕННЫЕ СЛОЕВ (короткие имена без IGconf_)
# ============================================================================

hybrid_raid_layout:
  rootfs_type: ext4                    # Тип корневой ФС (ext4, btrfs, f2fs)
  root_part_size: 2G                   # Размер root раздела
  boot_part_size: 200M                 # Размер boot раздела
  encryption_enabled: y                # Включить LUKS шифрование
  key_method: file                     # Метод хранения ключа
  key_size: 512                        # Размер ключа LUKS (бит)
  ssd_ids: "ata-SAMSUNG_HD204UI_S1XWJ1LZ100000,ata-SAMSUNG_HD204UI_S1XWJ1LZ100001"  # SSD device IDs
  pmap: clear                          # Тип provision map

# ============================================================================
# КОНФИГУРАЦИЯ УСТРОЙСТВА И ОБРАЗА
# ============================================================================

device:
  layer: rpi5

image:
  layer: hybrid-raid-layout
  name: test-hybrid-raid-layout

# ============================================================================
# СЛОИ СИСТЕМЫ (только ссылки)
# ============================================================================

layer:
  base: bookworm-minbase
