# Example configuration for MBR Boot + MD RAID1 + LUKS2 + Btrfs image
# This creates a Raspberry Pi image with:
# - MBR boot partition on SD card
# - MD RAID1 on two SATA SSDs
# - LUKS2 encryption on the RAID
# - Btrfs root filesystem

device:
  layer: rpi5
  hostname: raid-server

image:
  layer: image-mbr-mdraid-luks-btrfs
  name: raid-encrypted-system
  boot_part_size: 200M
  # Use device names (less reliable, but simple)
  mdraid_devices: /dev/sda,/dev/sdb
  # OR use disk UUIDs (more reliable, recommended)
  # mdraid_uuids: 12345678-1234-1234-1234-123456789012,87654321-4321-4321-4321-210987654321
  luks_keyfile: /boot/luks-key
  compression: zstd

layer:
  base: bookworm-minbase
  device: radxa-sata-penta-hat
  sys-apps: btrfs
  mdadm: mdadm
  security: system-monitoring
  sbom: sbom-base

# Radxa SATA Penta HAT configuration
radxa_sata:
  pcie_gen3: y        # Enable PCIe Gen 3.0 for maximum performance
  initramfs_sata: y   # Enable initramfs SATA initialization

# Security hardening for encrypted system
security:
  enable_encryption: y
  secure_boot: y

# LUKS encryption
cryptsetup:
  enable: y

# Btrfs filesystem
btrfs:
  enable: y

# RAID management (supports degraded mode for reliability)
mdadm:
  enable: y

# SBOM generation
sbom:
  enable: y
  provider: syft
