# Пример конфигурации с MD RAID1 + LUKS2 + Btrfs + Docker (Debian Trixie)
# Использование: rpi-image-gen build -c examples/config-mdraid-luks-btrfs-docker-trixie.yaml

device:
  layer: rpi5  # Raspberry Pi 5 с Radxa SATA Penta HAT
  user1: docker-user

image:
  layer: image-mbr-mdraid-luks-btrfs
  boot_part_size: 200M
  mdraid_devices: /dev/sda,/dev/sdb  # SATA SSD диски для RAID1
  luks_keyfile: /boot/luks-key

layer:
  base: trixie-minbase              # Debian Trixie как основа
  device: radxa-sata-penta-hat      # Обязателен для SATA SSD
  sys-apps: btrfs                   # Обязателен для Btrfs
  mdadm: mdadm                      # Обязателен для RAID
  docker: docker-debian-trixie      # Docker с оптимизациями для Btrfs

# Дополнительные параметры Docker
docker:
  trust_user1: y                    # Разрешить пользователю запускать Docker без sudo
