# Базовая конфигурация Hybrid RAID Layout без шифрования
# Подходит для большинства сценариев использования

device:
  layer: pi5
  hostname: my-raid-server

image:
  layer: hybrid-raid-layout
  name: basic-raid-image
  boot_part_size: 200M
  root_part_size: 4G

layer:
  base: bookworm-minbase
  security: apparmor-core

hybrid_raid_luks:
  encryption_enabled: n
  rootfs_type: ext4
  pmap: clear
  ssd_ids: "ata-SAMSUNG_HD204UI_S1XWJ1LZ100000,ata-SAMSUNG_HD204UI_S1XWJ1LZ100001"
