# Конфигурация Hybrid RAID Layout для разработки
# Минимальный размер + инструменты разработки

device:
  layer: pi5
  hostname: dev-raid-server

image:
  layer: hybrid-raid-layout
  name: dev-raid-image
  boot_part_size: 200M
  root_part_size: 2G

layer:
  base: bookworm-minbase
  development: full-dev-tools

hybrid_raid_luks:
  encryption_enabled: n
  rootfs_type: ext4
  pmap: clear
  ssd_ids: "ata-SAMSUNG_HD204UI_S1XWJ1LZ100000,ata-SAMSUNG_HD204UI_S1XWJ1LZ100001"
