# Конфигурация Hybrid RAID Layout с LUKS2 шифрованием
# Для сценариев, требующих защиты данных

device:
  layer: pi5
  hostname: encrypted-raid-server

image:
  layer: hybrid-raid-layout
  name: encrypted-raid-image
  boot_part_size: 200M
  root_part_size: 4G

layer:
  base: bookworm-minbase
  security: apparmor-core

hybrid_raid_luks:
  encryption_enabled: y
  key_method: file
  key_size: 512
  rootfs_type: btrfs
  pmap: crypt
  ssd_ids: "ata-SAMSUNG_HD204UI_S1XWJ1LZ100000,ata-SAMSUNG_HD204UI_S1XWJ1LZ100001"
