#!/bin/bash
#
# customize05-pkgs - RAID package installation
# Installs necessary packages for RAID array support
#
# Parameters:
#   $1 - chroot path
#
# Returns:
#   0 - success
#   1 - installation error
#

set -eu

# Base packages for all RAID types
pkgs=(dosfstools)  # mdadm is already installed by raid-base layer

# Additional packages based on filesystem type
case $IGconf_image_rootfs_type in
    ext4)  pkgs+=(e2fsprogs) ;;
    btrfs) pkgs+=(btrfs-progs) ;;
    f2fs)  pkgs+=(f2fs-tools) ;;
esac

# Install packages in chroot environment
chroot $1 apt install -y "${pkgs[@]}"