# Пример конфигурации UFW firewall для общей безопасности
# Enterprise-grade firewall для базовой сетевой защиты

device:
  layer: rpi5
  hostname: secure-server

image:
  layer: image-rpios
  name: enterprise-firewall
  compression: zstd

layer:
  base: bookworm-minbase
  security: ufw              # Включение UFW firewall слоя
  network: systemd-net-min   # Базовая сетевая конфигурация
  monitoring: system-monitoring  # Системы мониторинга
  sbom: sbom-base           # SBOM для compliance

# Полная конфигурация UFW firewall для enterprise окружения
ufw:
  enable: y  # Включить firewall

  # Политики по умолчанию (строгая безопасность)
  default_incoming: deny   # Запрещать все входящие по умолчанию
  default_outgoing: allow  # Разрешать все исходящие по умолчанию

  # Разрешенные сервисы (используют стандартные порты)
  allow_services: ssh,http,https,dns,ntp

  # Дополнительные разрешенные порты для веб-сервисов
  allow_ports: "8080/tcp,8443/tcp"  # Веб-интерфейсы

  # Разрешенные IP адреса/сети (локальная сеть + доверенные сети)
  allow_ips: "192.168.0.0/16,10.0.0.0/8,172.16.0.0/12"

  # Заблокированные IP (нежелательные сети)
  block_ips: "203.0.113.0/24,198.51.100.0/24"  # Примеры заблокированных сетей

  # Уровень логирования (средний для баланса безопасности и производительности)
  logging: medium  # off, low, medium, high, full

  # Поддержка IPv6
  ipv6_support: y            # Поддержка IPv6

# Мониторинг системы
monitoring:
  prometheus: y
  grafana: y
  node_exporter: y
  alertmanager: y

# SBOM для аудита и compliance
sbom:
  enable: y
  provider: syft
  detailed_scan: y

# Дополнительные меры безопасности (опционально)
# security:
#   enable_encryption: y
#   secure_boot: y
#   apparmor: y
#   fail2ban: y
