# Пример конфигурации password-policies для enterprise системы
device:
  layer: rpi5
  hostname: enterprise-server

image:
  layer: image-rpios
  name: enterprise-password-policies
  compression: zstd

layer:
  base: bookworm-minbase
  security: password-policies

# Полная настройка политик паролей для enterprise
password_policies:
  enable: y                            # Включить политики
  pass_max_days: 60                    # Смена пароля каждые 60 дней
  pass_min_days: 7                     # Минимум 7 дней между сменами
  pass_warn_age: 14                    # Предупреждение за 14 дней
  inactive: 15                         # Блокировать через 15 дней неактивности
  account_expiry: 180                  # Аккаунт истекает через 180 дней
  root_password_expiry: 30             # Root пароль меняется каждые 30 дней
  lock_inactive_users: y               # Блокировать неактивных пользователей
  password_history_remember: 10        # Запоминать 10 паролей
  password_consecutive_characters: 2   # Максимум 2 подряд одинаковых
  password_max_sequential_characters: 2 # Максимум 2 подряд последовательных
  password_last_change_past: 15        # Принудительная смена через 15 дней
  password_failed_lockout: 3           # Блокировка после 3 неудачных попыток
  password_unlock_time: 300            # 5 минут блокировки

# Дополнительные security слои
layer:
  base: bookworm-minbase
  security: apparmor
  security: ufw
  security: auditd
  security: sysctl-hardening
  security: pam-hardening

# AppArmor для MAC
apparmor:
  enable: y
  mode: enforce
  system_monitoring: y

# Firewall
ufw:
  enable: y
  default_incoming: deny
  default_outgoing: allow
  allow_services: ssh,http,https
  logging: medium

# Audit daemon
auditd:
  enable: y
  max_log_file: 8
  space_left: 75

# System hardening
sysctl_hardening:
  enable: y
  ptrace_restrict: y
  aslr_enable: y
  tcp_syn_cookies: y

# PAM hardening
pam_hardening:
  enable: y
  pwquality_enable: y
  pwquality_minlen: 16
  pwquality_dcredit: -1
  pwquality_ucredit: -1
  pwquality_lcredit: -1
  pwquality_ocredit: -1
  pwquality_retry: 3
  faillock_enable: y
  faillock_deny: 5
  faillock_unlock_time: 900
  limits_enable: y
