# Пример конфигурации PAM hardening для enterprise системы
device:
  layer: rpi5
  hostname: enterprise-server

image:
  layer: image-rpios
  name: enterprise-pam-hardened
  compression: zstd

layer:
  base: bookworm-minbase
  security: pam-hardening

# Полная настройка PAM hardening для enterprise
pam_hardening:
  enable: y                        # Включить PAM hardening
  pwquality_enable: y              # Проверка силы паролей
  pwquality_minlen: 16             # Длинные пароли
  pwquality_dcredit: -1            # Минимум 1 цифра
  pwquality_ucredit: -1            # Минимум 1 заглавная
  pwquality_lcredit: -1            # Минимум 1 строчная
  pwquality_ocredit: -1            # Минимум 1 специальный символ
  pwquality_retry: 3               # 3 попытки ввода
  faillock_enable: y               # Блокировка аккаунтов
  faillock_deny: 5                 # 5 неудачных попыток
  faillock_unlock_time: 900        # 15 минут блокировки
  limits_enable: y                 # Ограничения ресурсов
  tally2_enable: y                 # Отслеживание неудачных попыток
  unix_auth_enable: y              # Unix аутентификация
  shadow_auth: y                   # Shadow пароли

# Дополнительные security слои
layer:
  base: bookworm-minbase
  security: apparmor
  security: ufw
  security: auditd
  security: sysctl-hardening

# AppArmor для MAC
apparmor:
  enable: y
  mode: enforce
  rpi_optimized: y

# Firewall
ufw:
  enable: y
  default_incoming: deny
  default_outgoing: allow
  allow_services: ssh,http,https
  logging: medium

# Audit daemon
auditd:
  enable: y
  max_log_file: 8
  space_left: 75

# System hardening
sysctl_hardening:
  enable: y
  ptrace_restrict: y
  aslr_enable: y
  tcp_syn_cookies: y
