# METABEGIN
# X-Env-Layer-Name: rpi5-server-config
# X-Env-Layer-Category: device
# X-Env-Layer-Desc: Raspberry Pi 5 optimized config.txt for server usage - disables HDMI, optimizes PCIe/USB, reduces power consumption
# X-Env-Layer-Version: 1.0.0
# X-Env-Layer-Requires: rpi-boot-firmware
#
# X-Env-VarPrefix: rpi5_server
#
# X-Env-Var-disable_hdmi: y
# X-Env-Var-disable_hdmi-Desc: Disable HDMI output for power savings in headless server operation
# X-Env-Var-disable_hdmi-Required: n
# X-Env-Var-disable_hdmi-Valid: bool
# X-Env-Var-disable_hdmi-Set: immediate
#
# X-Env-Var-disable_wifi: y
# X-Env-Var-disable_wifi-Desc: Disable WiFi interface for security and power savings
# X-Env-Var-disable_wifi-Required: n
# X-Env-Var-disable_wifi-Valid: bool
# X-Env-Var-disable_wifi-Set: immediate
#
# X-Env-Var-disable_bluetooth: y
# X-Env-Var-disable_bluetooth-Desc: Disable Bluetooth interface for security and power savings
# X-Env-Var-disable_bluetooth-Required: n
# X-Env-Var-disable_bluetooth-Valid: bool
# X-Env-Var-disable_bluetooth-Set: immediate
#
# X-Env-Var-disable_audio: y
# X-Env-Var-disable_audio-Desc: Disable audio interfaces for server operation
# X-Env-Var-disable_audio-Required: n
# X-Env-Var-disable_audio-Valid: bool
# X-Env-Var-disable_audio-Set: immediate
#
# X-Env-Var-pcie_max_speed: y
# X-Env-Var-pcie_max_speed-Desc: Enable PCIe Gen 3.0 for maximum NVMe SSD performance
# X-Env-Var-pcie_max_speed-Required: n
# X-Env-Var-pcie_max_speed-Valid: bool
# X-Env-Var-pcie_max_speed-Set: immediate
#
# X-Env-Var-usb_max_performance: y
# X-Env-Var-usb_max_performance-Desc: Enable USB 3.0 high-performance mode
# X-Env-Var-usb_max_performance-Required: n
# X-Env-Var-usb_max_performance-Valid: bool
# X-Env-Var-usb_max_performance-Set: immediate
#
# X-Env-Var-disable_unused_interfaces: y
# X-Env-Var-disable_unused_interfaces-Desc: Disable SPI, I2C, I2S interfaces typically not needed on servers
# X-Env-Var-disable_unused_interfaces-Required: n
# X-Env-Var-disable_unused_interfaces-Valid: bool
# X-Env-Var-disable_unused_interfaces-Set: immediate
# METAEND
---
mmdebstrap:
  customize-hooks:
    # Raspberry Pi 5 Server Configuration
    - |
      set -eu
      CONFIG_FILE="$1/boot/firmware/config.txt"

      # Add server optimizations header if not present
      if ! grep -q "# Raspberry Pi 5 Server Optimized Configuration" "$CONFIG_FILE" 2>/dev/null; then
        echo "# Raspberry Pi 5 Server Optimized Configuration" >> "$CONFIG_FILE"
        echo "# Generated by rpi5-server-config layer" >> "$CONFIG_FILE"
        echo "" >> "$CONFIG_FILE"
      fi

      # Disable HDMI for power savings
      if [ "${IGconf_rpi5_server_disable_hdmi:-y}" = "y" ]; then
        echo "# Disable HDMI for power savings in headless operation" >> "$CONFIG_FILE"
        echo "hdmi_blanking=1" >> "$CONFIG_FILE"
        echo "hdmi_ignore_hotplug=1" >> "$CONFIG_FILE"
        echo "hdmi_ignore_composite=1" >> "$CONFIG_FILE"
        echo "hdmi_ignore_cec=1" >> "$CONFIG_FILE"
        echo "" >> "$CONFIG_FILE"
      fi

      # Enable PCIe Gen 3.0 for maximum NVMe SSD performance
      if [ "${IGconf_rpi5_server_pcie_max_speed:-y}" = "y" ]; then
        echo "# Enable PCIe Gen 3.0 for maximum NVMe SSD performance" >> "$CONFIG_FILE"
        echo "dtparam=pciex1_gen=3" >> "$CONFIG_FILE"
        echo "" >> "$CONFIG_FILE"
      fi

      # Enable USB 3.0 high-performance mode
      if [ "${IGconf_rpi5_server_usb_max_performance:-y}" = "y" ]; then
        echo "# Enable USB 3.0 high-performance mode" >> "$CONFIG_FILE"
        echo "usb_max_current_enable=1" >> "$CONFIG_FILE"
        echo "" >> "$CONFIG_FILE"
      fi

      # Disable unused interfaces for server operation
      if [ "${IGconf_rpi5_server_disable_unused_interfaces:-y}" = "y" ]; then
        echo "# Disable unused interfaces for server operation" >> "$CONFIG_FILE"
        echo "#dtparam=i2c_arm=off" >> "$CONFIG_FILE"
        echo "#dtparam=i2s=off" >> "$CONFIG_FILE"
        echo "#dtparam=spi=off" >> "$CONFIG_FILE"
        echo "" >> "$CONFIG_FILE"
      fi

      # Disable WiFi interface
      if [ "${IGconf_rpi5_server_disable_wifi:-y}" = "y" ]; then
        echo "# Disable WiFi interface" >> "$CONFIG_FILE"
        echo "dtoverlay=disable-wifi" >> "$CONFIG_FILE"
        echo "" >> "$CONFIG_FILE"
      fi

      # Disable Bluetooth interface
      if [ "${IGconf_rpi5_server_disable_bluetooth:-y}" = "y" ]; then
        echo "# Disable Bluetooth interface" >> "$CONFIG_FILE"
        echo "dtoverlay=disable-bt" >> "$CONFIG_FILE"
        echo "" >> "$CONFIG_FILE"
      fi

      # Disable audio interfaces
      if [ "${IGconf_rpi5_server_disable_audio:-y}" = "y" ]; then
        echo "# Disable audio interfaces" >> "$CONFIG_FILE"
        echo "dtparam=audio=off" >> "$CONFIG_FILE"
        echo "" >> "$CONFIG_FILE"
      fi

      # Server performance optimizations
      echo "# Server performance optimizations" >> "$CONFIG_FILE"
      echo "arm_boost=1" >> "$CONFIG_FILE"
      echo "gpu_mem=16" >> "$CONFIG_FILE"
      echo "" >> "$CONFIG_FILE"

      # Disable unnecessary services for memory savings
      echo "# Disable unnecessary services for memory savings" >> "$CONFIG_FILE"
      echo "disable_camera_led=1" >> "$CONFIG_FILE"
      echo "disable_splash=1" >> "$CONFIG_FILE"
      echo "" >> "$CONFIG_FILE"
