# METABEGIN
# X-Env-Layer-Name: rpi5-server-config
# X-Env-Layer-Category: device
# X-Env-Layer-Desc: Raspberry Pi 5 optimized config.txt for server usage - disables HDMI, optimizes PCIe/USB, reduces power consumption
# X-Env-Layer-Version: 1.0.0
# X-Env-Layer-Requires: rpi5,rpi-boot-firmware
#
# X-Env-VarPrefix: rpi5_server
#
# X-Env-Var-disable_hdmi: y
# X-Env-Var-disable_hdmi-Desc: Disable HDMI output for power savings in headless server operation
# X-Env-Var-disable_hdmi-Required: n
# X-Env-Var-disable_hdmi-Valid: bool
# X-Env-Var-disable_hdmi-Set: immediate
#
# X-Env-Var-disable_wifi: y
# X-Env-Var-disable_wifi-Desc: Disable WiFi interface for security and power savings
# X-Env-Var-disable_wifi-Required: n
# X-Env-Var-disable_wifi-Valid: bool
# X-Env-Var-disable_wifi-Set: immediate
#
# X-Env-Var-disable_bluetooth: y
# X-Env-Var-disable_bluetooth-Desc: Disable Bluetooth interface for security and power savings
# X-Env-Var-disable_bluetooth-Required: n
# X-Env-Var-disable_bluetooth-Valid: bool
# X-Env-Var-disable_bluetooth-Set: immediate
#
# X-Env-Var-disable_audio: y
# X-Env-Var-disable_audio-Desc: Disable audio interfaces for server operation
# X-Env-Var-disable_audio-Required: n
# X-Env-Var-disable_audio-Valid: bool
# X-Env-Var-disable_audio-Set: immediate
#
# X-Env-Var-pcie_max_speed: y
# X-Env-Var-pcie_max_speed-Desc: Enable PCIe Gen 3.0 for maximum NVMe SSD performance
# X-Env-Var-pcie_max_speed-Required: n
# X-Env-Var-pcie_max_speed-Valid: bool
# X-Env-Var-pcie_max_speed-Set: immediate
#
# X-Env-Var-usb_max_performance: y
# X-Env-Var-usb_max_performance-Desc: Enable USB 3.0 high-performance mode
# X-Env-Var-usb_max_performance-Required: n
# X-Env-Var-usb_max_performance-Valid: bool
# X-Env-Var-usb_max_performance-Set: immediate
#
# X-Env-Var-disable_unused_interfaces: y
# X-Env-Var-disable_unused_interfaces-Desc: Disable SPI, I2C, I2S interfaces typically not needed on servers
# X-Env-Var-disable_unused_interfaces-Required: n
# X-Env-Var-disable_unused_interfaces-Valid: bool
# X-Env-Var-disable_unused_interfaces-Set: immediate
#
# X-Env-Var-optimize_performance: n
# X-Env-Var-optimize_performance-Desc: Enable additional performance optimizations (may increase power consumption)
# X-Env-Var-optimize_performance-Required: n
# X-Env-Var-optimize_performance-Valid: bool
# X-Env-Var-optimize_performance-Set: immediate
#
# X-Env-Var-security_hardening: n
# X-Env-Var-security_hardening-Desc: Enable security hardening features (disables USB mass storage, UART)
# X-Env-Var-security_hardening-Required: n
# X-Env-Var-security_hardening-Valid: bool
# X-Env-Var-security_hardening-Set: immediate
# METAEND
---
mmdebstrap:
  customize-hooks:
    # Raspberry Pi 5 Server Configuration
    - |
      echo "# Raspberry Pi 5 Server Optimized Configuration" >> $1/boot/firmware/config.txt
      echo "# Generated by rpi5-server-config layer" >> $1/boot/firmware/config.txt
      echo "" >> $1/boot/firmware/config.txt

    # Отключение HDMI для экономии энергии
    - |
      if [ "${IGconf_rpi5_server_disable_hdmi}" = "y" ]; then
        echo "# Disable HDMI for power savings in headless operation" >> $1/boot/firmware/config.txt
        echo "hdmi_blanking=1" >> $1/boot/firmware/config.txt
        echo "hdmi_ignore_hotplug=1" >> $1/boot/firmware/config.txt
        echo "hdmi_ignore_composite=1" >> $1/boot/firmware/config.txt
        echo "hdmi_ignore_cec=1" >> $1/boot/firmware/config.txt
        echo "" >> $1/boot/firmware/config.txt
      fi

    # Максимальная производительность PCIe (NVMe SSD)
    - |
      if [ "${IGconf_rpi5_server_pcie_max_speed}" = "y" ]; then
        echo "# Enable PCIe Gen 3.0 for maximum NVMe SSD performance" >> $1/boot/firmware/config.txt
        echo "dtparam=pciex1_gen=3" >> $1/boot/firmware/config.txt
        echo "" >> $1/boot/firmware/config.txt
      fi

    # Максимальная производительность USB 3.0
    - |
      if [ "${IGconf_rpi5_server_usb_max_performance}" = "y" ]; then
        echo "# Enable USB 3.0 high-performance mode" >> $1/boot/firmware/config.txt
        echo "usb_max_current_enable=1" >> $1/boot/firmware/config.txt
        echo "" >> $1/boot/firmware/config.txt
      fi

    # Отключение ненужных интерфейсов
    - |
      if [ "${IGconf_rpi5_server_disable_unused_interfaces}" = "y" ]; then
        echo "# Disable unused interfaces for server operation" >> $1/boot/firmware/config.txt
        echo "#dtparam=i2c_arm=off" >> $1/boot/firmware/config.txt
        echo "#dtparam=i2s=off" >> $1/boot/firmware/config.txt
        echo "#dtparam=spi=off" >> $1/boot/firmware/config.txt
        echo "" >> $1/boot/firmware/config.txt
      fi

    # Отключение WiFi
    - |
      if [ "${IGconf_rpi5_server_disable_wifi}" = "y" ]; then
        echo "# Disable WiFi interface" >> $1/boot/firmware/config.txt
        echo "dtoverlay=disable-wifi" >> $1/boot/firmware/config.txt
        echo "" >> $1/boot/firmware/config.txt
      fi

    # Отключение Bluetooth
    - |
      if [ "${IGconf_rpi5_server_disable_bluetooth}" = "y" ]; then
        echo "# Disable Bluetooth interface" >> $1/boot/firmware/config.txt
        echo "dtoverlay=disable-bt" >> $1/boot/firmware/config.txt
        echo "" >> $1/boot/firmware/config.txt
      fi

    # Отключение аудио
    - |
      if [ "${IGconf_rpi5_server_disable_audio}" = "y" ]; then
        echo "# Disable audio interfaces" >> $1/boot/firmware/config.txt
        echo "dtparam=audio=off" >> $1/boot/firmware/config.txt
        echo "" >> $1/boot/firmware/config.txt
      fi

    # Серверные оптимизации производительности
    - |
      echo "# Server performance optimizations" >> $1/boot/firmware/config.txt
      echo "arm_boost=1" >> $1/boot/firmware/config.txt
      echo "gpu_mem=16" >> $1/boot/firmware/config.txt
      echo "" >> $1/boot/firmware/config.txt

    # Отключение ненужных служб для экономии памяти
    - |
      echo "# Disable unnecessary services for memory savings" >> $1/boot/firmware/config.txt
      echo "disable_camera_led=1" >> $1/boot/firmware/config.txt
      echo "disable_splash=1" >> $1/boot/firmware/config.txt
      echo "" >> $1/boot/firmware/config.txt

    # Дополнительные оптимизации производительности для серверного использования
    - |
      if [ "${IGconf_rpi5_server_optimize_performance}" = "y" ]; then
        echo "# Additional performance optimizations for server workloads" >> $1/boot/firmware/config.txt
        echo "# Increase CPU frequency for better server performance" >> $1/boot/firmware/config.txt
        echo "# Note: This may increase power consumption but improves performance" >> $1/boot/firmware/config.txt
        echo "" >> $1/boot/firmware/config.txt
      fi

    # Безопасность: отключение потенциально опасных интерфейсов
    - |
      if [ "${IGconf_rpi5_server_security_hardening}" = "y" ]; then
        echo "# Security hardening for server environment" >> $1/boot/firmware/config.txt
        echo "# Disable USB mass storage gadget for security" >> $1/boot/firmware/config.txt
        echo "dtoverlay=disable-mass-storage" >> $1/boot/firmware/config.txt
        echo "# Disable serial console access for security" >> $1/boot/firmware/config.txt
        echo "enable_uart=0" >> $1/boot/firmware/config.txt
        echo "" >> $1/boot/firmware/config.txt
      fi
